/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.ivoa.vodml.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'net.ivoa.vodml.gradle.plugin.greeting' plugin.
 */
internal class VodmlGradlePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply(VodmlGradlePlugin.VODML_PLUGIN_ID)

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
