<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:map="http://www.ivoa.net/xml/vodml-binding/v0.9.1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:vf="http://www.ivoa.net/xml/VODML/functions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:vo-dml="http://www.ivoa.net/xml/VODML/v1">

    <!-- this stylesheet should be included in stylesheets that want to make use of the binding
    mechanism. It should be included after the $binding variable containing the list of binding files has been set -->
    <xsl:import href="common-binding.xsl"/>

    <!--read the mapping from the bindings -->
    <xsl:variable name="mapping">
        <xsl:message>setting mapping</xsl:message>
        <map:mappedModels>
            <xsl:for-each select="tokenize($binding,',')">
                <xsl:message><xsl:value-of select="."/></xsl:message>
                <xsl:copy-of
                        select="document(normalize-space(.))/map:mappedModels/model" />
            </xsl:for-each>
        </map:mappedModels>
    </xsl:variable>

    <!-- load all models at start -->
    <xsl:variable name="models">
        <xsl:message>setting models</xsl:message>
        <xsl:for-each select="$mapping/map:mappedModels/model">
            <xsl:choose>
                <xsl:when test="file"> <!-- prefer local file for reading defn -->
                    <xsl:message>opening file <xsl:value-of select="file"/></xsl:message>
                    <xsl:copy-of
                            select="document(file)/vo-dml:model" />
                </xsl:when>
                <xsl:when test="url">
                    <xsl:copy-of
                            select="document(url)/vo-dml:model" />
                </xsl:when>
                <xsl:otherwise>
                    <xsl:message>Model <xsl:value-of select="vodml-id" />has neither url nor file, hence no artifacts will be generated.</xsl:message>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:for-each>
    </xsl:variable>
<!-- some important global variables -->
    <xsl:variable name="themodelname" select="/vo-dml:model/name"/>
    <xsl:variable name="vodmlauthor" select="'@author generated by https://github.com/ivoa/vo-dml tools'"/>
    <xsl:variable name="lt">&lt;</xsl:variable>
    <xsl:variable name="gt">&gt;</xsl:variable>
    <xsl:variable name="isRdbSingleInheritance" as="xsd:boolean" select="vf:isRdbSingleTable(/vo-dml:model/name)"/>
    <xsl:variable name="discriminatorColumnLength" as="xsd:int">
        <xsl:choose>
            <xsl:when test="$mapping/map:mappedModels/model[name=$themodelname]/rdb/@discriminatorColumnLength">
                <xsl:value-of select="$mapping/map:mappedModels/model[name=$themodelname]/rdb/@discriminatorColumnLength"/>
            </xsl:when>
            <xsl:otherwise>32</xsl:otherwise>
        </xsl:choose>
    </xsl:variable>
</xsl:stylesheet>
