<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE stylesheet [
<!ENTITY cr "<xsl:text>
</xsl:text>">
<!ENTITY bl "<xsl:text> </xsl:text>">
]>

<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:vo-dml="http://www.ivoa.net/xml/VODML/v1"
                xmlns:vf="http://www.ivoa.net/xml/VODML/functions"
                xmlns:exsl="http://exslt.org/common"
                xmlns:bnd="http://www.ivoa.net/xml/vodml-binding/v0.9.1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                extension-element-prefixes="exsl"
                exclude-result-prefixes="bnd"
                >
<!--
  This XSLT script transforms a data model in VO-DML/XML representation to
  Python pydantic models using xsdata-pydantic for XML/JSON serialisation.

  N.B this script is fragile to indentation (because of python - there should probably be a better way to get indentation to work)

  needs Python 3.10+ and xsdata-pydantic

  Paul Harrison (JBO)
-->


  <xsl:output method="xml" encoding="UTF-8" indent="yes" />
  <xsl:output name="python" method="text" encoding="UTF-8" omit-xml-declaration="yes"/>

  <xsl:strip-space elements="*" />


  <xsl:param name="lastModified"/>
  <xsl:param name="lastModifiedText"/>
  <xsl:param name="output_root" />
  <xsl:param name="vo-dml_package" select="'org.ivoa.vodml.model'"/>
  <xsl:param name="binding"/>
  <xsl:param name="isMain"/>
  <xsl:include href="binding_setup.xsl" />

  <!-- double-quote shorthand (used in value-of to embed quotes in generated Python) -->
  <xsl:variable name="dq">"</xsl:variable>
  <!-- single-quote shorthand -->
  <xsl:variable name="sq">'</xsl:variable>
  <xsl:variable name="root_package" select="$mapping/bnd:mappedModels/model[name=$themodelname]/python-package"/>
  <xsl:variable name="root_package_dir" select="replace($root_package,'[.]','/')"/> <!-- not windows friendly! -->


  <!-- main pattern : processes for root node model -->
  <xsl:template match="/">
    <xsl:message>Generating Pydantic - considering models <xsl:value-of select="string-join($models/vo-dml:model/name,' and ')"/></xsl:message>
    <xsl:apply-templates mode="intro"/>
  </xsl:template>

  <!-- model pattern : generates gen-log and processes nodes package -->
  <xsl:template match="vo-dml:model" mode="intro">
    <xsl:message>
-------------------------------------------------------------------------------------------------------
-- Generating Pydantic code for model <xsl:value-of select="name"/> [<xsl:value-of select="title"/>].
-- last modification date of the model <xsl:value-of select="lastModified"/>
-------------------------------------------------------------------------------------------------------
    </xsl:message>

    <xsl:if test="not($mapping/bnd:mappedModels/model[name=$themodelname])">
      <xsl:message terminate="yes">
        There is no binding for model <xsl:value-of select="$themodelname"/>
      </xsl:message>
    </xsl:if>

    <!-- write __init__.py in the package path elements -->
    <xsl:variable name="path" select="subsequence(reverse(tokenize($root_package, '\.')),2)" />
    <xsl:for-each select="1 to count($path)">
      <xsl:variable name="subpath" select="concat(string-join(reverse(subsequence($path, current())),'/'),'/__init__.py')" />
      <xsl:result-document href="{$subpath}" format="python" omit-xml-declaration="yes">
        <xsl:value-of select="concat('# Generated by gradle vodml tools ',current-dateTime())"/>
      </xsl:result-document>
    </xsl:for-each>

    <xsl:apply-templates select="." mode="packageDesc"/>
    <xsl:apply-templates select="." mode="content"/>
  </xsl:template>


  <xsl:template match="vo-dml:model|package" mode="content">
    <variable name="root_package_dir" select="$root_package_dir"/>
    <xsl:variable name="file" select="concat($root_package_dir, '/',string-join(./ancestor-or-self::*/name,'_') , '.py')"/>
    <xsl:variable name="package-vodml-ref" select="concat(./ancestor-or-self::vo-dml:model/name,':',string-join(./ancestor-or-self::package/name,'.'))"/>
    <xsl:message>package = <xsl:value-of select="concat(name,' ',$file,' ',$package-vodml-ref)"/></xsl:message>
    <xsl:result-document href="{$file}" format="python">
      <xsl:value-of select="concat('# Generated by gradle vodml tools ',current-dateTime())"/>

<xsl:text>
from __future__ import annotations
from typing import Optional, List, Any, Union
from enum import Enum
from pydantic import BaseModel, ConfigDict, field_serializer
from xsdata_pydantic.fields import field as xsfield
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
from xsdata.formats.dataclass.parsers import XmlParser
import xsdata_pydantic.hooks.class_type  # register pydantic support with xsdata
</xsl:text>

<xsl:text>
# base class to make swapping from pydantic-xml easier in tests -
# TODO this could go in runtime - anyway, does not need to be class method really
class _VodmlXmlBase(BaseModel):
    """Base class providing Pydantic BaseModel with xsdata XML serialisation."""
    model_config = ConfigDict(arbitrary_types_allowed=True)

    def to_xml(self, pretty_print: bool = False) -> bytes:
        config = SerializerConfig(indent="  " if pretty_print else None)
        ctx = XmlContext(class_type="pydantic")
        return XmlSerializer(config=config, context=ctx).render(self).encode("utf-8")

    @classmethod
    def from_xml(cls, xml_bytes: bytes):
        ctx = XmlContext(class_type="pydantic")
        data = xml_bytes.decode("utf-8") if isinstance(xml_bytes, bytes) else xml_bytes
        return XmlParser(context=ctx).from_string(data, cls)


</xsl:text>
      <!-- cross-package imports -->
      <xsl:for-each select="distinct-values((*/((attribute|reference|composition|constraint[contains(@xsi:type,'SubsettedRole')])/datatype/vodml-ref)|*/extends/vodml-ref))">
        <xsl:if test="not(vf:isPythonBuiltin(.))">
          <xsl:variable name="typepackage" select="concat(substring-before(.,':'),':',string-join(tokenize(substring-after(.,':'),'\.')[position() != last()],'.'))"/>
          <xsl:if test="(vf:hasMapping(.,'python') or $typepackage != $package-vodml-ref)">
            <xsl:variable name="fulltype" select="vf:FullPythonType(.,true())"/>
              <xsl:value-of select="concat('from ',vf:PythonModule(.),' import ',tokenize($fulltype, '\.')[last()],$nl)"/>
          </xsl:if>
        </xsl:if>
      </xsl:for-each>
      <xsl:apply-templates select="primitiveType" mode="file"/>
      <xsl:apply-templates select="enumeration" mode="file"/>
      <xsl:apply-templates select="objectType|dataType" mode="file">
        <xsl:sort select="vf:numberSupertypes(vf:asvodmlref(current()))" data-type="number"/>
      </xsl:apply-templates>
      <xsl:if test="self::vo-dml:model">
        <xsl:apply-templates select="." mode="model-wrapper"/>
      </xsl:if>
    </xsl:result-document>
    <xsl:apply-templates select="package" mode="content"/>

  </xsl:template>


  <xsl:template match="objectType|dataType|enumeration|primitiveType" mode="file">
    <xsl:variable name="vodml-ref" select="vf:asvodmlref(.)"/>
    <xsl:variable name="mappedtype" select="vf:findmapping($vodml-ref,'python')"/>
    <xsl:choose>
      <xsl:when test="not($mappedtype) or $mappedtype = ''">
        <xsl:message>Writing pydantic code for <xsl:value-of select="name"/> base=<xsl:value-of select="vf:baseTypes($vodml-ref)/name"/> haschildren=<xsl:value-of select="vf:hasSubTypes($vodml-ref)"/></xsl:message>
        <xsl:apply-templates select="." mode="content"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:message>1) Mapped type for <xsl:value-of select="$vodml-ref"/> = '<xsl:value-of select="$mappedtype"/>'</xsl:message>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>


  <!-- objectType → xsdata-pydantic BaseModel class -->
  <xsl:template match="objectType" mode="content">
    <xsl:variable name="vodml-ref" select="vf:asvodmlref(current())"/>
    <xsl:variable name="modelName" select="ancestor-or-self::vo-dml:model/name"/>
    <xsl:variable name="nsprefix" select="vf:xsdNsPrefix($modelName)"/>
    <xsl:text>

</xsl:text>
    <xsl:call-template name="vodmlAnnotation"/>
<xsl:text>class </xsl:text><xsl:value-of select="name"/><xsl:text>(</xsl:text><xsl:choose>
      <xsl:when test="extends"><xsl:value-of select="vf:PythonType(extends/vodml-ref)"/></xsl:when>
      <xsl:otherwise>_VodmlXmlBase</xsl:otherwise>
    </xsl:choose><xsl:text>):
    class Meta:
        name = "</xsl:text><xsl:value-of select="name"/><xsl:text>"
</xsl:text>
    <xsl:text>    """
    * </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    *
    * </xsl:text><xsl:value-of select="name()"/><xsl:text>: </xsl:text><xsl:value-of select="name"/><xsl:text>
    *
    * </xsl:text><xsl:value-of select="$vodmlauthor"/><xsl:text>
    """
</xsl:text>
    <xsl:if test="vf:referredTo($vodml-ref) and not(attribute/constraint[ends-with(@xsi:type,':NaturalKey')]) and not(extends)">
    <xsl:text>    id: Optional[str] = xsfield({'type': 'Attribute', 'name': '_id'}, default=None)  # an identifier field to allow referring to this object from other objects (e.g. via reference fields) without needing to embed it
</xsl:text>
    </xsl:if>
    <xsl:if test="not(@abstract='true') and (extends or vf:hasSubTypes($vodml-ref))">
    <xsl:value-of select="concat('    xsi_type: Optional[str] = xsfield({',$sq,'type',$sq,': ',$sq,'Attribute',$sq,', ',$sq,'name',$sq,': ',$sq,'type',$sq,', ',$sq,'namespace',$sq,': ',$sq,'http://www.w3.org/2001/XMLSchema-instance',$sq,'}, default=',$dq,name,$dq,')')"/>
    <xsl:text>
</xsl:text>
    </xsl:if>
    <xsl:apply-templates select="(attribute|composition|reference)[multiplicity/minOccurs=1 and multiplicity/maxOccurs=1]" mode="declare"/>
    <xsl:apply-templates select="(attribute|composition|reference)[not(multiplicity/minOccurs=1 and multiplicity/maxOccurs=1)]" mode="declare"/>
    <xsl:apply-templates select="constraint[ends-with(@xsi:type,':SubsettedRole')]" mode="declare"/>
    <xsl:apply-templates select="reference" mode="serializer"/>
    <xsl:if test="not(attribute) and not(composition) and not(reference) and not(extends) and not(constraint[ends-with(@xsi:type,':SubsettedRole')])">
    <xsl:text>    pass
</xsl:text>
    </xsl:if>
  </xsl:template>


  <!-- dataType → xsdata-pydantic BaseModel class -->
  <xsl:template match="dataType" mode="content">
    <xsl:variable name="vodml-ref" select="vf:asvodmlref(current())"/>
    <xsl:variable name="modelName" select="ancestor-or-self::vo-dml:model/name"/>
    <xsl:variable name="nsprefix" select="vf:xsdNsPrefix($modelName)"/>
    <xsl:text>

</xsl:text>
    <xsl:call-template name="vodmlAnnotation"/>
<xsl:text>class </xsl:text><xsl:value-of select="name"/><xsl:text>(</xsl:text><xsl:choose>
      <xsl:when test="extends"><xsl:value-of select="vf:PythonType(extends/vodml-ref)"/></xsl:when>
      <xsl:otherwise>_VodmlXmlBase</xsl:otherwise>
    </xsl:choose><xsl:text>):
    class Meta:
        name = "</xsl:text><xsl:value-of select="name"/><xsl:text>"
</xsl:text>
    <xsl:text>    """
    * </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    *
    * </xsl:text><xsl:value-of select="name()"/><xsl:text>: </xsl:text><xsl:value-of select="name"/><xsl:text>
    *
    * </xsl:text><xsl:value-of select="$vodmlauthor"/><xsl:text>
    """
</xsl:text>
    <xsl:if test="not(@abstract='true') and (extends or vf:hasSubTypes($vodml-ref))">
    <xsl:value-of select="concat('    xsi_type: Optional[str] = xsfield({',$sq,'type',$sq,': ',$sq,'Attribute',$sq,', ',$sq,'name',$sq,': ',$sq,'type',$sq,', ',$sq,'namespace',$sq,': ',$sq,'http://www.w3.org/2001/XMLSchema-instance',$sq,'}, default=',$dq,name,$dq,')')"/>
    <xsl:text>
</xsl:text>
    </xsl:if>
    <xsl:apply-templates select="(attribute|reference)[multiplicity/minOccurs=1 and multiplicity/maxOccurs=1]" mode="declare"/>
    <xsl:apply-templates select="(attribute|reference)[not(multiplicity/minOccurs=1 and multiplicity/maxOccurs=1)]" mode="declare"/>
    <xsl:apply-templates select="constraint[ends-with(@xsi:type,':SubsettedRole')]" mode="declare"/>
    <xsl:apply-templates select="reference" mode="serializer"/>
    <xsl:if test="not(attribute) and not(reference) and not(extends) and not(constraint[ends-with(@xsi:type,':SubsettedRole')])">
    <xsl:text>    pass
</xsl:text>
    </xsl:if>
  </xsl:template>


  <!-- enumeration → Python Enum class -->
  <xsl:template match="enumeration" mode="content">
    <xsl:text>


class </xsl:text><xsl:value-of select="concat(name,'(str, Enum):')"/>
    <xsl:text>
    """
    * </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    *
    * Enumeration </xsl:text><xsl:value-of select="name"/><xsl:text> :
    *
    * </xsl:text><xsl:value-of select="$vodmlauthor"/><xsl:text>
    """
</xsl:text>
    <xsl:apply-templates select="literal"/>
&cr;
  </xsl:template>


  <!-- primitiveType → simple xsdata-pydantic BaseModel with a value field -->
  <xsl:template match="primitiveType" mode="content">
    <xsl:variable name="valuetype">
      <xsl:choose>
        <xsl:when test="extends">
          <xsl:value-of select="vf:PythonType(extends/vodml-ref)"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:message>Primitive type <xsl:value-of select="name"/> represented as str</xsl:message>
          <xsl:value-of select="'str'"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:call-template name="vodmlAnnotation"/>
    <xsl:text>

class </xsl:text><xsl:value-of select="name"/><xsl:text>(_VodmlXmlBase):
    class Meta:
        name = "</xsl:text><xsl:value-of select="name"/><xsl:text>"
    """
    *  </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    *  PrimitiveType </xsl:text><xsl:value-of select="name"/><xsl:text> :
    *
    *  </xsl:text><xsl:value-of select="$vodmlauthor"/><xsl:text>
    """

    value: </xsl:text><xsl:value-of select="$valuetype"/><xsl:text> = xsfield({'type': 'Element', 'name': 'value', 'namespace': ''})


</xsl:text>
  </xsl:template>


  <!-- ======== field declarations ======== -->

  <!-- single-valued attribute: required or optional -->
  <xsl:template match="attribute" mode="declare">
    <xsl:variable name="type" select="vf:PythonType(datatype/vodml-ref)"/>
    <xsl:variable name="vodml-ref" select="vf:asvodmlref(.)"/>
    <!-- include xsdata format string for special types (e.g. datetime) -->
    <xsl:variable name="fmt" select="vf:PythonFormat(datatype/vodml-ref)"/>
    <xsl:variable name="fmtpart" select="if (string-length($fmt) gt 0) then concat(', ',$sq,'format',$sq,': ',$sq,$fmt,$sq) else ''"/>
    <xsl:if test="not(vf:isSubSetted($vodml-ref))">
      <xsl:text>
    </xsl:text>
      <xsl:call-template name="vodmlAnnotation"/>
      <xsl:choose>
        <xsl:when test="multiplicity/maxOccurs = -1 or number(multiplicity/maxOccurs) gt 1">
          <!-- list-valued attribute -->
          <xsl:value-of select="concat(name, ': List[', $type, '] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,$fmtpart,'}, default_factory=list)')"/>
        </xsl:when>
        <xsl:when test="vf:isOptional(.)">
          <xsl:value-of select="concat(name, ': Optional[', $type, '] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,$fmtpart,'}, default=None)')"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select="concat(name, ': ', $type, ' = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,$fmtpart,'})')"/>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:text>
    """
    Attribute </xsl:text><xsl:value-of select="name"/><xsl:text> : multiplicity </xsl:text><xsl:apply-templates select="multiplicity" mode="tostring"/>
      <xsl:text>
    </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    """
</xsl:text>
    </xsl:if>
  </xsl:template>


  <!-- SubsettedRole constraint: add a narrowed-type field -->
  <xsl:template match="constraint[ends-with(@xsi:type,':SubsettedRole')]" mode="declare">
    <xsl:variable name="subsetted" select="$models/key('ellookup',current()/role/vodml-ref)"/>
    <xsl:if test="name($subsetted)='attribute' and datatype/vodml-ref != $subsetted/datatype/vodml-ref">
      <xsl:variable name="stype" select="vf:PythonType(datatype/vodml-ref)"/>
      <xsl:variable name="sname" select="tokenize(role/vodml-ref/text(),'[.]')[last()]"/>
      <xsl:text>
    </xsl:text>
      <xsl:value-of select="concat($sname, ': ', $stype, ' = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,$sname,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'})')"/>
      <xsl:text>
    """
    * Attribute </xsl:text><xsl:value-of select="$sname"/><xsl:text> : subsetted
    *
    </xsl:text><xsl:apply-templates select="$subsetted" mode="desc"/><xsl:text>.
    """
</xsl:text>
    </xsl:if>
  </xsl:template>


  <!-- multi-valued composition -->
  <xsl:template match="composition[multiplicity/maxOccurs != 1]" mode="declare">
    <xsl:variable name="type" select="vf:PythonType(datatype/vodml-ref)"/>
    <xsl:call-template name="vodmlAnnotation"/>
    <xsl:text>
    </xsl:text>
    <xsl:value-of select="concat(name, ': List[', $type, '] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'}, default_factory=list)')"/>
    <xsl:text>
    """
    *
    * Composition </xsl:text><xsl:value-of select="name"/><xsl:text> : ( Multiplicity : </xsl:text><xsl:apply-templates select="multiplicity" mode="tostring"/><xsl:text>)
    </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    *
    """

</xsl:text>
  </xsl:template>


  <!-- single-valued composition -->
  <xsl:template match="composition[multiplicity/maxOccurs = 1]" mode="declare">
    <xsl:variable name="type" select="vf:PythonType(datatype/vodml-ref)"/>
    <xsl:call-template name="vodmlAnnotation"/>
    <xsl:text>
    </xsl:text>
    <xsl:choose>
      <xsl:when test="multiplicity/minOccurs = 0">
        <xsl:value-of select="concat(name, ': Optional[', $type, '] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'}, default=None)')"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="concat(name, ': ', $type, ' = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'})')"/>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:text>
    """
    * Composition </xsl:text><xsl:value-of select="name"/><xsl:text> : ( Multiplicity : </xsl:text><xsl:apply-templates select="multiplicity" mode="tostring"/><xsl:text>)
    *
    *    </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    """

</xsl:text>
  </xsl:template>


  <!-- reference: serialised as the referenced object's key or as an embedded element -->
  <xsl:template match="reference" mode="declare">
    <xsl:variable name="type" select="vf:PythonType(datatype/vodml-ref)"/>
    <xsl:call-template name="vodmlAnnotation"/>
    <xsl:text>
    </xsl:text>
    <xsl:choose>
      <xsl:when test="multiplicity/maxOccurs != 1">
        <xsl:value-of select="concat(name, ': List[Union[str, ', $type, ']] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'}, default_factory=list)')"/>
      </xsl:when>
      <xsl:when test="vf:isOptional(.)">
        <xsl:value-of select="concat(name, ': Optional[Union[str, ', $type, ']] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'}, default=None)')"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="concat(name, ': Union[str, ', $type, '] = xsfield({',$sq,'type',$sq,': ',$sq,'Element',$sq,', ',$sq,'name',$sq,': ',$sq,name,$sq,', ',$sq,'namespace',$sq,': ',$sq,$sq,'})')"/>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:text>
    """
    * Reference </xsl:text><xsl:value-of select="name"/><xsl:text> :
    * </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    * ( Multiplicity : </xsl:text><xsl:apply-templates select="multiplicity" mode="tostring"/><xsl:text>) """
</xsl:text>
  </xsl:template>

  <xsl:template match="reference" mode="serializer">
    <xsl:variable name="method-name" select="replace(name,'[^A-Za-z0-9_]','_')"/>
      <!--TODO - need to add custom serializer to handle serialisation of references as either embedded elements or as keys (ie. as in the java case if an instance has already been serialized then just emit an id reference - otherwise emit the full object) -->
  </xsl:template>

  <xsl:template match="vo-dml:model" mode="model-wrapper">
    <xsl:variable name="modelName" select="name"/>
    <xsl:variable name="modelClass" select="concat(vf:upperFirst(name),'Model')"/>
    <xsl:variable name="refsClass" select="concat(vf:upperFirst(name),'Refs')"/>
    <xsl:variable name="rootTag" select="concat(name,'Model')"/>
    <xsl:variable name="rootPrefix" select="vf:xsdNsPrefix($modelName)"/>
    <xsl:variable name="rootNs" select="vf:xsdNs($modelName)"/>
    <xsl:variable name="references-vodmlref" select="vf:refsToSerialize($modelName)"/>
    <xsl:variable name="contentTypes" as="element()*" select="vf:contentToSerialize($modelName)"/>


        <!-- import all content from other packages in the same model (but not the current package) - needed to resolve references across packages -->

        <xsl:for-each select="$contentTypes">
            <xsl:variable name="vodml-ref" select="vf:asvodmlref(current())"/>
            <xsl:variable name="isInThisFile" select="current()/parent::vo-dml:model[name =$modelName]"/>
            <xsl:if test="not($isInThisFile) and not(vf:isPythonBuiltin($vodml-ref)) ">
                <xsl:value-of select="concat('from ',vf:PythonModule($vodml-ref),' import ',tokenize(vf:PythonType($vodml-ref), '\.')[last()],$nl)"/>
            </xsl:if>
        </xsl:for-each>
      <xsl:for-each select="$references-vodmlref">
          <xsl:variable name="vodml-ref" select="current()"/>
          <xsl:variable name="el" select="$models/key('ellookup',$vodml-ref)"/>
          <xsl:variable name="isInThisFile" select="$el/parent::vo-dml:model[name =$modelName]"/>
          <xsl:if test="not($isInThisFile) and not(vf:isPythonBuiltin($vodml-ref))">
              <xsl:value-of select="concat('from ',vf:PythonModule($vodml-ref),' import ',tokenize(vf:PythonType($vodml-ref), '\.')[last()],$nl)"/>
          </xsl:if>
      </xsl:for-each>

      <xsl:text>

class </xsl:text><xsl:value-of select="$refsClass"/><xsl:text>(_VodmlXmlBase):
    class Meta:
        name = "refs"
</xsl:text>
    <xsl:for-each select="$references-vodmlref">
      <xsl:variable name="rtype" select="vf:PythonType(.)"/>
      <xsl:variable name="rtag" select="vf:lowerFirst($models/key('ellookup',current())/name)"/>
      <xsl:text>    </xsl:text><xsl:value-of select="$rtag"/><xsl:text>: List[</xsl:text><xsl:value-of select="$rtype"/><xsl:text>] = xsfield({'type': 'Element', 'name': '</xsl:text><xsl:value-of select="$rtag"/><xsl:text>', 'namespace': ''}, default_factory=list)
</xsl:text>
    </xsl:for-each>
    <xsl:if test="empty($references-vodmlref)">
      <xsl:text>    pass
</xsl:text>
    </xsl:if>
    <xsl:text>
class </xsl:text><xsl:value-of select="$modelClass"/><xsl:text>(_VodmlXmlBase):
    class Meta:
        name = "</xsl:text><xsl:value-of select="$rootTag"/><xsl:text>"
        namespace = "</xsl:text><xsl:value-of select="$rootNs"/><xsl:text>"
    refs: Optional[</xsl:text><xsl:value-of select="$refsClass"/><xsl:text>] = xsfield({'type': 'Element', 'name': 'refs', 'namespace': ''}, default=None)
</xsl:text>
    <xsl:for-each select="$contentTypes">
      <xsl:variable name="ctype" select="vf:PythonType(vf:asvodmlref(current()))"/>
      <xsl:variable name="ctag" select="vf:lowerFirst($models/key('ellookup',vf:asvodmlref(current()))/name)"/>
      <xsl:text>    </xsl:text><xsl:value-of select="$ctag"/><xsl:text>: List[</xsl:text><xsl:value-of select="$ctype"/><xsl:text>] = xsfield({'type': 'Element', 'name': '</xsl:text><xsl:value-of select="$ctag"/><xsl:text>', 'namespace': ''}, default_factory=list)
</xsl:text>
    </xsl:for-each>
  </xsl:template>


  <!-- enumeration literal -->
  <xsl:template match="literal">
    <xsl:variable name="up">
      <xsl:call-template name="constant">
        <xsl:with-param name="text" select="name"/>
      </xsl:call-template>
    </xsl:variable>
    <xsl:text>
    </xsl:text><xsl:value-of select="$up"/><xsl:text> = "</xsl:text><xsl:value-of select="name"/><xsl:text>"
    """
    * Value </xsl:text><xsl:value-of select="name"/><xsl:text> :
    *
    * </xsl:text><xsl:apply-templates select="." mode="desc"/><xsl:text>
    """</xsl:text>
  </xsl:template>


  <xsl:template match="*" mode="desc">
    <xsl:choose>
      <xsl:when test="count(description) > 0 and normalize-space(description) != 'TODO : Missing description : please, update your UML model asap.'">
        <xsl:value-of select="description" disable-output-escaping="yes"/>
        <xsl:if test="not(ends-with(normalize-space(description/text()), '.'))">
          <xsl:value-of select="'.'"/>
        </xsl:if>
      </xsl:when>
      <xsl:otherwise/>
    </xsl:choose>
  </xsl:template>


  <xsl:template match="vo-dml:model" mode="packageDesc">
    <xsl:variable name="file" select="concat($root_package_dir,'/__init__.py')"/>
    <xsl:message>Writing package info file <xsl:value-of select="$file"/></xsl:message>
    <xsl:result-document href="{$file}" format="python">
"""
      <xsl:value-of select="title"/>

      <xsl:value-of select="description"/>
"""
    </xsl:result-document>
  </xsl:template>


  <xsl:template name="vodmlAnnotation">
    <!-- nothing for now -->
  </xsl:template>


</xsl:stylesheet>
