site_name: VO-DML Tools Guide
docs_dir: guide
repo_url: https://github.com/ivoa/vo-dml
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
nav:
  - Home: index.md
  - Getting Started:
      - Installation: Installation.md
      - Configuration: QuickStart.md
  - Transformers:
      - Introduction: Transformers.md
      - Documentation: Documentation.md
      - Java Generation: JavaCodeGeneration.md
      - Serialization: Serialization.md
  - Writing Models:
      - Introduction: modelling/index.md
      - VODSL : modelling/VODSL.md
      - Eclipse Editor: modelling/EclipseVODSL.md
      - UML : modelling/UML.md
  - Model Design:
      - Introduction : modelling/designIntro.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
