site_name: VO-DML Tools Guide
docs_dir: guide
repo_url: 'https://github.com/ivoa/vo-dml'
edit_uri: 'edit/master/doc/guide/'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.action.edit
nav:
  - Home: index.md
  - Getting Started:
      - Installation: Installation.md
      - Configuration: QuickStart.md
      - Commands: Commands.md
  - Derived Products:
      - Introduction: Transformers.md
      - Binding: Binding.md
      - Documentation: Documentation.md
      - Java Generation: JavaCodeGeneration.md
      - Python Generation: PythonCodeGeneration.md
      - Serialization: Serialization.md
  - Writing Models:
      - Introduction: modelling/modellingIntro.md
      - VODSL : modelling/VODSL.md
      - Eclipse Editor: modelling/EclipseVODSL.md
      - UML : modelling/UML.md
      - Generation from other sources : modelling/TransformingToVODML.md
  - Model Design:
      - Introduction : modelling/designIntro.md
      - Validation: modelling/Validation.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      url_download: true