name: Standard Document PDF Preview generation

on:
  push:
    branches: [20-update-vo-dml-standard-document]
  pull_request:
    branches: [20-update-vo-dml-standard-document]
jobs:
   build:
     runs-on: ubuntu-24.04

     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup dependencies
         run: |
           sudo apt -y update
           sudo apt -y install pandoc wkhtmltopdf
       - name: make the document
         run: |
           make -C doc/std VO-DML.pdf
       - name: upload the std doc
         uses: actions/upload-artifact@v4
         with:
           name: VO-DML-WD
           path: doc/std/VO-DML.pdf
       - name: Creates a release in GitHub and uploads attachments
         env:
           GITHUB_TOKEN: ${{ github.TOKEN }}
           shell: bash
         run: | 
           gh release -n "latest working draft" create WD-1.1 doc/std/VO-DML.pdf 
