name: Standard Document PDF Preview generation

on:
  push:
    branches: [20-update-vo-dml-standard-document]
  pull_request:
    branches: [20-update-vo-dml-standard-document]
jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Setup dependencies
         run: |
           sudo apt -y update
           sudo apt -y install pandoc wkhtmltopdf
       - name: make the document
         run: |
           make -C doc/std VO-DML.pdf
       - name: upload the std doc
         uses: actions/upload-artifact@v4
         with:
           name: VO-DML-WD
           path: doc/std/VO-DML.pdf
