# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run tests on gradle plugin sample

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build java runtime with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: false
          arguments: |
            :java:publishToMavenLocal  
            -PskipSigning=True
      - name: Build ivoa model with Gradle
        uses:  gradle/actions/setup-gradle@v3
        with:
          cache-disabled: false
          arguments: |
            :ivoa:publishToMavenLocal  
            -PskipSigning=True
      - name: Test sample model with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: false
          arguments: |
            :gradletooling:vodml-sample:test
            -PskipSigning=True
