
package org.ivoa.vodml.stdtypes;
        


      /**
      *  a string identifier.
      *  PrimitiveType stringIdentifier :
      *
      *  @author generated by https://github.com/ivoa/vo-dml tools
      */
      
@org.ivoa.vodml.annotation.VoDml(id="ivoa:stringIdentifier", role=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="a string identifier")
    @jakarta.persistence.Embeddable

    @jakarta.xml.bind.annotation.XmlType( name = "stringIdentifier")
  
      public class StringIdentifier  implements java.io.Serializable {

        private static final long serialVersionUID = 1L;

        /**  representation */
        @jakarta.xml.bind.annotation.XmlValue
        @jakarta.persistence.Column(name="val")
        protected String value;

        /**
         * Creates a new stringIdentifier Primitive Type instance, wrapping a base type.
         *
         * @param v the value.
         */
        public StringIdentifier(final String v) {
            this.value = v;
        }
      /**
      * no arg constructor.
      */
      protected StringIdentifier() {}

      /**
      * copy constructor.
       * @param c the other to copy.
      */
      public StringIdentifier(StringIdentifier c)
      {
         this(c.value);
      }

      /**
         * Return the representation of this primitive (value)
         * @return string representation of this primitive( value)
         */
        public final String value() {
            return this.value;
        }

        /**
         * Return the string representation of this primitive value
         * @see #value()
         * @return string representation of this primitive
         */
        @Override
        public final String toString() {
            return value().toString();
        }
              

      }
  