
package org.ivoa.vodml.stdtypes;
        


      /**
      *  Must conform to definition of unit in VOUnit spec.
      *  PrimitiveType Unit :
      *
      *  originally generated by https://github.com/ivoa/vo-dml tools - now hand edited.
       *  TODO - make this class conform to the VO Units spec - would be nice to have lots of static instances for each unit...
      */
      
@org.ivoa.vodml.annotation.VoDml(id="ivoa:Unit", role=org.ivoa.vodml.annotation.VodmlRole.primitiveType)
          

        @org.eclipse.microprofile.openapi.annotations.media.Schema(description="Must conform to definition of unit in VOUnit spec.")
    @javax.persistence.Embeddable

    @javax.xml.bind.annotation.XmlType( name = "Unit")
  
      public class Unit implements java.io.Serializable {

        private static final long serialVersionUID = 1L;

        /**  representation */
        @javax.xml.bind.annotation.XmlValue
        private String value;

        /**
         * Creates a new Unit Primitive Type instance, wrapping a base type.
         *
         * @param v 
         */
        public Unit(final String v) {
            this.value = v;
        }
        /**
         * no arg constructor.
         */
        protected Unit() {}

        /**
         * Return the representation of this primitive (value)
         * @return string representation of this primitive( value)
         */
        public final String value() {
            return this.value;
        }

        /**
         * Return the string representation of this primitive value
         * @see #value()
         * @return string representation of this primitive
         */
        @Override
        public final String toString() {
            return value().toString();
        }
              

      }
  